title: "Testing GitHub Pages: using DartPad"
description: >-
  Just playing around with GitHub Pages and DartPad.
source: "./"
incremental: false

# GitHub pages theme
remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme
theme: jekyll-theme-cayman

# Disable source link in header
github:
  is_project_page: false