title: "Testing GitHub Pages: using DartPad"
description: >-
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
source: "./"
incremental: false

# GitHub pages theme
remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme
theme: jekyll-theme-cayman

# Disable source link in header
github:
  is_project_page: false